Initial PR for bloom analyses
knightlab-analyses/bloom-analyses pull request #1
Opened 2016-10-25 03:20 UTC by mortonjt

@wasade, @amnona - would you like to sanity check this and merge if appropriate?

2016-10-25 03:53 UTC, wasade requested changes

2016-10-25 03:53 UTC, wasade commented on bloom/filter_seqs_from_biom.py
> +        yield seq[:length]
What about seqs less than `length`?

2016-10-25 03:53 UTC, wasade commented on bloom/filter_seqs_from_biom.py
> +    filter_seqs = set([str(s) for s in seqs])
Set comprehension?

2016-10-25 03:53 UTC, wasade commented on bloom/filter_seqs_from_biom.py
> +    table.filter(bloom_filter, axis='observation')
Can this drop samples which no longer have sequence as well?

I believe `filter` can accept an iterable or set so I don't think you need to pass a function for the first filter

Strongly recommend against calling anything in here "bloom filter" as that is a well recognized data structure.

2016-10-25 03:53 UTC, wasade commented on bloom/filter_seqs_from_biom.py
> +        parser=argparse.ArgumentParser(
4 space please

2016-10-25 03:53 UTC, wasade commented on bloom/filter_seqs_from_biom.py
> +        seqs = skbio.read(args.fasta, format='fasta')
Why not just let skbio resolve as to allow support for fastq or compressed data?

2016-10-25 03:53 UTC, wasade commented on bloom/filter_seqs_from_biom.py
> +                outtable.to_hdf5(f, "filterbiomseqs")
Ident differs

2016-10-25 03:53 UTC, wasade commented on bloom/filter_seqs_from_biom.py
> +    table.filter(bloom_filter, axis='observation')
Shouldn't this filter be inverted?

2016-10-25 03:53 UTC, wasade commented on bloom/filter_seqs_from_biom.py
> +        outtable = remove(table, seqs)
I don't believe this function exists

2016-10-25 03:53 UTC, wasade commented on ipynb/bloom_example.ipynb
> +    "`30_seqs.fna.gz` file."
Why is this 30? The three sets discussed in the manuscript are 10, 15, and 20?

2016-10-25 03:53 UTC, wasade commented on ipynb/bloom_example.ipynb
> +    "        outtable.to_hdf5(f, \"filterbiomseqs\")"
Different indent

2016-10-25 04:06 UTC, mortonjt commented on bloom/filter_seqs_from_biom.py
> +    table.filter(bloom_filter, axis='observation')
XD

Yeah, I was really confused when I first heard that term.

Not sure about the filter.  We want to keep sequences that aren't blooms right?

2016-10-25 04:07 UTC, mortonjt commented on bloom/filter_seqs_from_biom.py
> +    filter_seqs = set([str(s) for s in seqs])
Done

2016-10-25 04:07 UTC, mortonjt commented on bloom/filter_seqs_from_biom.py
> +        yield seq[:length]
ValueError raised

2016-10-25 04:07 UTC, mortonjt commented on bloom/filter_seqs_from_biom.py
> +        parser=argparse.ArgumentParser(
:/ yeah...

2016-10-25 04:07 UTC, mortonjt commented on bloom/filter_seqs_from_biom.py
> +        seqs = skbio.read(args.fasta, format='fasta')
agreed

2016-10-25 04:07 UTC, mortonjt commented on bloom/filter_seqs_from_biom.py
> +        outtable = remove(table, seqs)
doh

2016-10-25 04:08 UTC, mortonjt commented on bloom/filter_seqs_from_biom.py
> +                outtable.to_hdf5(f, "filterbiomseqs")
fixed

2016-10-25 04:08 UTC, mortonjt commented on ipynb/bloom_example.ipynb
> +    "`30_seqs.fna.gz` file."
@amnona why is this the case?

2016-10-25 04:10 UTC, wasade commented on bloom/filter_seqs_from_biom.py
> +    table.filter(bloom_filter, axis='observation')
Right, so shouldn't it be inverted...?

2016-10-25 04:14 UTC, mortonjt commented on bloom/filter_seqs_from_biom.py
> +    table.filter(bloom_filter, axis='observation')
If that's the case - no.

Because filter command only keeps the ids that pass the filter, not vice versa. 
I am verifying this in the unittest.

2016-10-25 04:20 UTC, mortonjt commented on ipynb/bloom_example.ipynb
> +    "        outtable.to_hdf5(f, \"filterbiomseqs\")"
Also fixed

2016-10-25 18:27 UTC, wasade commented
Any id which evals true (ie a bloom) is retained. I thought the point was
to remove the blooms?

On Oct 24, 2016 21:14, "Jamie Morton" <notifications@github.com> wrote:

> *@mortonjt* commented on this pull request.
> ------------------------------
>
> In bloom/filter_seqs_from_biom.py
> <https://github.com/knightlab-analyses/bloom-analyses/pull/1>:
>
> > +def remove_seqs(table, seqs):
> +    """
> +    Parameters
> +    ----------
> +    table : biom.Table
> +       Input biom table
> +    seqs : generator, skbio.Sequence
> +       Iterator of sequence objects to be removed from the biom table.
> +
> +    Return
> +    ------
> +    biom.Table
> +    """
> +    filter_seqs = set([str(s) for s in seqs])
> +    bloom_filter = lambda v, i, m: i in filter_seqs
> +    table.filter(bloom_filter, axis='observation')
>
> If that's the case - no.
>
> Because filter command only keeps the ids that pass the filter, not vice
> versa.
> I am verifying this in the unittest.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/knightlab-analyses/bloom-analyses/pull/1>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAc8si2MGV1_xj_SeyKWAKvDsczOJsS4ks5q3YIXgaJpZM4KfhL9>
> .
>

2016-10-25 19:07 UTC, mortonjt commented
@wasade can you clarify the last two comments?  I'm not sure what the context is ...

2016-10-25 19:11 UTC, wasade commented
they're inline on the commit

https://github.com/mortonjt/bloom_analyses/commit/42efa4f36b9f56d0987ab47ff7ac9e5f588d956c

2016-10-25 21:38 UTC, amnona commented on ipynb/bloom_example.ipynb
> +    "`30_seqs.fna.gz` file."
30_seqs.fna.gz is the fasta file for the whole grain feces study :)

2016-10-25 21:39 UTC, amnona commented
👍

2016-10-26 03:25 UTC, mortonjt commented
@wasade I tried to address your comments.  Could you verify that everything has been addressed and merge if ok?  Thanks!

2016-10-27 00:25 UTC, merged

2016-10-27 00:29 UTC, mortonjt commented
Thanks @wasade !